export interface Usuario {
  id: number;
  nome: string;
  email: string;
  senha: string;
  dt_nascimento: string;
  rg: string;
  orcamentosCount: number;
  procedimentosCount: number;
  ultimoRetorno: string;
  cpf: string;
  id_tipo_usuario: number;
  estado_civil: string;
  sexo: string;
  endereco: string;
  num_endereco: string;
  complemento: string;
  cidade: string;
  bairro: string;
  cep: string;
  naturalidade: string;
  nacionalidade: string;
  raca: string;
  filhos: number;
  telefone: string;
  celular: string;
  profissao: string;
  local_trabalho: string;
  instagram: string;
  facebook: string;
  ic_ativo: boolean;
  createdAt: string;
  updatedAt: string;
  anamnese: {
    id: number;
    usuario_id: number;
    comp_trat_odon: boolean | null;
    comp_trat_odon_obs: string | null;
    em_trat_medico: boolean | null;
    em_trat_medico_obs: string | null;
    transfusao: boolean | null;
    transfusao_obs: string | null;
    doenca_grave: boolean | null;
    doenca_grave_obs: string | null;
    alergia_geral: boolean | null;
    alergia_geral_obs: string | null;
    hospitalizado: boolean | null;
    hospitalizado_obs: string | null;
    submetido_cirurgia: boolean | null;
    cirurgia_obs: string | null;
    recebeu_anestesia: boolean | null;
    comp_anestesia: boolean | null;
    comp_anestesia_obs: string | null;
    dor_dente: boolean | null;
    dor_dente_obs: string | null;
    protese_cardiaca: boolean | null;
    protese_cardiaca_obs: string | null;
    sangramento_anormal: boolean | null;
    sangramento_anormal_obs: string | null;
    tomando_medicamento: boolean | null;
    tomando_medicamento_obs: string | null;
    cond_diabetes: boolean | null;
    cond_dist_renais: boolean | null;
    cond_dormir: boolean | null;
    cond_coracao: boolean | null;
    cond_pressao: boolean | null;
    cond_ulcera: boolean | null;
    cond_alergia: boolean | null;
    cond_vitaminas: boolean | null;
    cond_hormonio: boolean | null;
    cond_anticoagulante: boolean | null;
    cond_sist_nervoso: boolean | null;
    cond_artrite: boolean | null;
    cond_anticonvulsivante: boolean | null;
    cond_dor_cabeca: boolean | null;
    alergia_med: boolean | null;
    alergia_med_obs: string | null;
    alerg_penincilina: boolean | null;
    tomou_benzetacil: boolean | null;
    alerg_sulfa: boolean | null;
    tomou_bactrim: boolean | null;
    alerg_ass: boolean | null;
    alerg_anestesico_loc: boolean | null;
    pressao_tipo: 'Baixa' | 'Alta' | 'Não sabe' | 'Normal' | null;
    sint_dor_cabeca: boolean | null;
    sint_tontura: boolean | null;
    sint_nauseas: boolean | null;
    sint_dor_nuca: boolean | null;
    sint_palpitacoes: boolean | null;
    sint_zumbidos: boolean | null;
    sint_perda_memoria: boolean | null;
    sint_perda_equilibrio: boolean | null;
    diabetico: 'SIM' | 'NÃO' | 'NÃO SABE' | null;
    diab_familia: boolean | null;
    emagreceu: boolean | null;
    come_muito: boolean | null;
    urina_freq: boolean | null;
    muita_sede: boolean | null;
    prob_respiratorio: boolean | null;
    resp_asma: boolean | null;
    resp_bronquite: boolean | null;
    resp_tosse: boolean | null;
    resp_tb: boolean | null;
    prob_cardiaco: 'SIM' | 'NÃO' | 'NÃO SABE' | null;
    card_dor_peito: boolean | null;
    card_dor_costas: boolean | null;
    card_cansa: boolean | null;
    card_arritmia: boolean | null;
    card_sopro: boolean | null;
    card_dorme_altura: boolean | null;
    card_incha_pe: boolean | null;
    prob_articulacoes: boolean | null;
    gravida: boolean | null;
    anticoncepcional: boolean | null;
    sangra_facil: boolean | null;
    hemofilico: boolean | null;
    sinusite: boolean | null;
    prob_estomago: boolean | null;
    xerostomia: boolean | null;
    dengue: boolean | null;
    estressado: boolean | null;
    abriu_boca: boolean | null;
    autoimune: boolean | null;
    possui_HIV: boolean | null;
    leucemia: boolean | null;
    epilepsia: boolean | null;
    toma_anticoag: boolean | null;
    marca_passo: boolean | null;
    anemia: 'SIM' | 'NÃO' | 'NÃO SABE' | null;
    vicio: boolean | null;
    fuma: boolean | null;
    bebe: boolean | null;
    range_dentes: boolean | null;
    aperta_dentes: boolean | null;
    usa_palito: boolean | null;
    usa_drogas: boolean | null;
    usa_drogas_obs: string | null;
    gu_problema: boolean | null;
    gu_insuficiencia: boolean | null;
    gu_calculo: boolean | null;
    gu_infeccao: boolean | null;
    gu_doenca_venerea: boolean | null;
    hepa: 'SIM' | 'NÃO' | 'NÃO SABE' | null;
    hepa_obs: string | null;
    outra_doenca: 'SIM' | 'NÃO' | 'NÃO SABE' | null;
    diarreia_cronica: boolean | null;
    febre_const: boolean | null;
    sudorese: boolean | null;
    cancer_pele: boolean | null;
    diabetes_desc: boolean | null;
    probl_cicatriz: boolean | null;
    doenca_cont: boolean | null;
    baixa_imun: boolean | null;
    dermatite: boolean | null;
    familia_info: string | null;
    createdAt: string;
    updatedAt: string;
  };
  examesComplementares: {
    id: number;
    usuario_id: number;
    peso: number | null;
    data_peso: string | null;
    tipo_sanguineo: string | null;
    pressao: string | null;
    data_pressao: string | null;
    createdAt: string;
    updatedAt: string;
  };
}
